--- #YAML:1.0
name:               Sys-Syslog
version:            0.29
abstract:           Perl interface to the UNIX syslog(3) calls
author:
    - Sebastien Aperghis-Tramoni <sebastien@aperghis.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Fcntl:           0
    File::Basename:  0
    File::Spec:      0
    POSIX:           0
    Socket:          0
    Test::More:      0
    XSLoader:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
