---
name: Sys-Syslog
version: 0.25
author:
  - 'Sebastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: Perl interface to the UNIX syslog(3) calls
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Fcntl: 0
  File::Basename: 0
  File::Spec: 0
  POSIX: 0
  Socket: 0
  XSLoader: 0
  perl: 5.005
build_requires:
  Test::More: 0
provides:
  Sys::Syslog:
    file: Syslog.pm
    version: 0.25
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
