--- #YAML:1.0
name:                Sys-Syslog
version:             0.24
abstract:            Perl interface to the UNIX syslog(3) calls
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
